name: update

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install
      run: pip install requests

    - name: Run script
      run: python filter.py

    - name: Commit + Force Sync
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"

        git add .

        git commit -m "auto update" || echo "no changes"

        git fetch origin main

        git reset --hard origin/main || true

        git add mci.txt

        git commit -m "auto update nodes" || echo "no changes"

        git push --force origin main
